apps/carrito/urls.py
from django.urls import path
from apps.carrito.views import carrito

app_name = 'Carrito'
urlpatterns = [
    path('', carrito, name =  'carrito')
    ]

apps/productos/urls.py
from django.urls import path
from apps.productos.views import ViewProducto,categorias,nuevoRegistro, editarRegistro, eliminarRegistro, nuevoRegistroCat, editarRegistroCat, eliminarRegistroCat, agregarCarrito

app_name = 'Productos'
urlpatterns = [
    path('listado', ViewProducto.as_view() , name =  'listado'),
    path('categorias', categorias , name =  'categorias'),

    #URLS Productos
    path('nuevoRegistro', nuevoRegistro, name="nuevoRegistro"),
    path('editarRegistro/<idProducto>', editarRegistro, name="editarRegistro"),
    path('eliminarRegistro/<idProducto>', eliminarRegistro, name="eliminarRegistro"),
    #URLS Categorias
    path('nuevoRegistroCat', nuevoRegistroCat, name="nuevoRegistroCat"),
    path('editarRegistrocat/<idCategoria>', editarRegistroCat, name="editarRegistroCat"),
    path('eliminarRegistrocat/<idCategoria>', eliminarRegistroCat, name="eliminarRegistroCat"),
    #agregarCarrito
    path('agregarCarrito/<idProducto>', agregarCarrito, name="agregarCarrito")
]

tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from tienda.views import index


urlpatterns = [
	path('', index),
    path('admin/', admin.site.urls),
    path('productos/', include('apps.productos.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('carrito/', include('apps.carrito.urls'))
]

apps/carrito/models.py
from django.db import models

# Create your models here.
class Carrito(models.Model):
	usuario = models.CharField(max_length=30)
	producto = models.IntegerField(default = 0)
	cantidad = models.IntegerField(default = 0)
	nombreProducto = models.CharField(max_length=30, default = 'Sin Nombre')
	precio = models.IntegerField(default = 0)

apps/productos/models.py
from django.db import models

# Create your models here.
class Producto(models.Model):
	nombre = models.CharField(max_length=30)
	codigo = models.IntegerField(default = 0)
	caracteristicas = models.CharField(max_length = 150, default = ' - Sin caracteristicas -')
	precio = models.IntegerField(default = 0)
	fechaDeRegistro = models.DateField(default = '2000-01-01')
	cantidad = models.IntegerField(default = 0)

class Categoria(models.Model):
	nombre = models.CharField(max_length=30)
	descripcion = models.CharField(max_length = 150, default = 'Sin descripción')
	fechaDeRegistro = models.DateField(default = '2000-01-01')

apps/productos/forms.py
from django import forms
from apps.productos.models import Producto, Categoria

class ProductoForm(forms.ModelForm):
	class Meta:
		model = Producto
		fields = [
			'nombre',
			'codigo',
			'caracteristicas',
			'precio',
			'fechaDeRegistro',
			'cantidad',
		]

		labels = {
			'nombre' : 'Nombre',
			'codigo' : 'Código',
			'caracteristicas' : 'Características',
			'precio' : 'Precio',
			'fechaDeRegistro' : 'Fecha de registro',
			'cantidad' : 'Cantidad',
		}

		widgets = {
			'nombre' : forms.TextInput(attrs={'class': 'form-control'}),
			'codigo' : forms.TextInput(attrs={'class': 'form-control'}),
			'caracteristicas' : forms.TextInput(attrs={'class': 'form-control'}),
			'precio' : forms.TextInput(attrs={'class': 'form-control'}),
			'fechaDeRegistro': forms.TextInput(attrs={'class': 'form-control'}),
			'cantidad': forms.TextInput(attrs={'class': 'form-control'}),
		}
#Formulario Categorías
class CategoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria
		fields = [
			'nombre',
			'descripcion',
			'fechaDeRegistro',
		]

		labels = {
			'nombre' : 'Nombre',
			'descripcion' : 'Descripción de la categoría',
			'fechaDeRegistro' : 'Fecha de registro',
		}

		widgets = {
			'nombre' : forms.TextInput(attrs={'class': 'form-control'}),
			'descripcion' :forms.TextInput(attrs={'class': 'form-control'}),
			'fechaDeRegistro': forms.TextInput(attrs={'class': 'form-control'}),
		}

class ProductoCarritoForm(forms.ModelForm):
	class Meta:
		model = Producto
		fields = [
			'nombre',
			'codigo',
			'caracteristicas',
			'precio',
			'fechaDeRegistro'
		]

		labels = {
			'nombre' : 'Nombre',
			'codigo' : 'Código',
			'caracteristicas' : 'Características',
			'precio' : 'Precio',
			'fechaDeRegistro' : 'Fecha de registro'
		}

		widgets = {
			'nombre' : forms.TextInput(attrs={'readonly': '', 'class': 'form-control'}),
			'codigo' : forms.TextInput(attrs={'readonly': '', 'class': 'form-control'}),
			'caracteristicas' : forms.TextInput(attrs={'readonly': '', 'class': 'form-control'}),
			'precio' : forms.TextInput(attrs={'readonly': '', 'class': 'form-control'}),
			'fechaDeRegistro': forms.TextInput(attrs={'readonly': '', 'class': 'form-control'})
		}
			

apps/carrito/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic  import ListView
from apps.carrito.models import Carrito

# Create your views here.

def carrito(request):
	contexto = { 
		'carrito': Carrito.objects.all()
	}
	return render(request, 'carrito/index.html', contexto)

'''def comprar(request, idUsuario):
	listaCompra = Carrito.objects.get(usuario = idUsuario)
	listaCompra.delete()
	return redirect('Productos:listado');'''

apps/productos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic  import ListView
from apps.productos.models import Producto, Categoria
from apps.carrito.models import Carrito
from apps.productos.forms import ProductoForm, CategoriaForm, ProductoCarritoForm
import MySQLdb

# Create your views here.

def listado(request):
	contexto = { 
		'productos': Producto.objects.all()
	}
	return render(request, 'productos/listado.html', contexto)

def categorias(request):
	contexto = { 
		'categorias': Categoria.objects.all()
	}
	return render(request, 'categorias/index.html', contexto)

class ViewProducto(ListView):
	model =  Producto
	template_name = 'productos/listado.html'


def nuevoRegistro(request):
	if request.method == 'POST':
		form = ProductoForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('Productos:listado');
	else:
		form = ProductoForm()
	return render(request, 'productos/ProductosFormulario.html', {'form' : form}) 
		

	form = ProductoForm()
	return render(request, 'productos/ProductosFormulario.html', {'form' : form})

def editarRegistro(request, idProducto):
	producto = Producto.objects.get(id = idProducto)
	if (request.method == 'GET'):
		form = ProductoForm(instance=producto)
	else:
		form = ProductoForm(request.POST, instance = producto)
		if form.is_valid():
			form.save();
		return redirect('Productos:listado')
	return render(request, 'productos/ProductosFormulario.html', {'form' : form})

def eliminarRegistro(request, idProducto):
	producto = Producto.objects.get(id = idProducto)
	producto.delete()
	return redirect('Productos:listado');

##
## -- Views Categorias
##

def nuevoRegistroCat(request):
	if request.method == 'POST':
		form = CategoriaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('Productos:categorias');
	else:
		form = CategoriaForm()
	return render(request, 'categorias/categoriasFormulario.html', {'form' : form}) 
		

	form = CategoriaForm()
	return render(request, 'productos/ProductosFormulario.html', {'form' : form})

def editarRegistroCat(request, idCategoria):
	categoria = Categoria.objects.get(id = idCategoria)
	if (request.method == 'GET'):
		form = CategoriaForm(instance=categoria)
	else:
		form = CategoriaForm(request.POST, instance = categoria)
		if form.is_valid():
			form.save();
		return redirect('Productos:categorias')
	return render(request, 'categorias/categoriasFormulario.html', {'form' : form})

def eliminarRegistroCat(request, idCategoria):
	categoria = Categoria.objects.get(id = idCategoria)
	categoria.delete()
	return redirect('Productos:categorias');


def agregarCarrito(request, idProducto):
	prod = Producto.objects.get(id = idProducto)
	user = request.user.id

	a = Carrito(producto=idProducto, usuario= user, nombreProducto= prod.nombre ,cantidad = '1', precio = prod.precio)
	a.save()
	return redirect('/');
	

tienda/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic  import ListView
from apps.productos.models import Producto, Categoria

# Create your views here.

def index(request):
	contexto = { 
		'categorias': Categoria.objects.all(),
		'productos': Producto.objects.all()
	}
	return render(request, 'index/index.html', contexto)

templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %} Proyecto {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	{% block extracss%}{% endblock %}
</head>
<body>
	{% block header %}
    <div class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
      <div class="container">
        <a href="/" class="navbar-brand">Tienda</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/productos/listado">Categorías</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/productos/categorias">Productos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/carrito">carrito</a>
            </li>
          </ul>

          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
              {% block login %}
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}" target="">Cerrar Sesión</a>
              {% else %}
              <a class="nav-link" href="{% url 'login' %}" target="">Iniciar Sesión</a>
              {% endif %}
              {% endblock %}
            </li>
          </ul>

        </div>
      </div>
    </div>
	{% endblock %}

    <div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-8 col-md-7 col-sm-6">
            <h1>Litera</h1>
          </div>
        </div>
      </div>

      <!-- Navbar
      ================================================== -->
      <div class="bs-docs-section clearfix">
        <div class="row">
          <div class="col-lg-12">
			{% block content %}
			{% endblock %}
            
          </div>
        </div>
      </div>


    </div>


<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.js' %}""></script> 
  

</body>
</html>

templates/carrito/index.html
{% extends 'base/index.html' %}
{% load staticfiles %}
}
{% block content %}


<div class="bs-component">
            	<table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Precio</th>
                  </tr>
                </thead>
                <tbody>
<script>
	total = 0
</script>
                  	{% for Carrito in carrito %}
                  	{% if user.id != Carrito.usuario%}
                  	<tr>
                  		<td>{{Carrito.id}}</td>
						<td>{{Carrito.nombreProducto}}</td>
                      	<td>{{Carrito.precio}}</td>
					</tr>
<script>
	total = total + {{Carrito.precio}}
	//alert(total);
</script>
							
							{% else %}
							<h3>No tienes productos en el carrito</h3>
							{% endif %}
					          
					          {% empty %}

					           <p>No hay productos</p>
					         {% endfor %}
              </table>
              <div class="total">
              </div>
            <a href="{%url 'comprar:comprar' Carrito.usuario }" class="btn btn-info">Comprar</a>
            </div>
<script>
	$( ".total" ).append( "<h1>Total: <span class='text-secondary'>" + total + "</span></h1>" );
</script>
{% endblock%}

templates/categorias/categoriasFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}
}
{% block content %}

<div class="container">
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-success">Guardar</button>
	</form>
</div>
{% endblock%}

templates/categorias/index.html
{% extends 'base/index.html' %}
{% load staticfiles %}
}
{% block content %}
      <div class="bs-docs-section clearfix">
        <div class="row">
          <div class="col-lg-12">
            <div class="page-header">
              <h1 id="navbars">Categorias</h1>
            </div>

            <div class="bs-component">
            	<table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Fecha de Registro</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                  </tr>
                </thead>
                
                <tbody>
                  	{% for Categoria in categorias %}
                  	<tr>
                  		<td>{{Categoria.id}}</td>
						          <td>{{Categoria.nombre}}</td>
                      <td>{{Categoria.descripcion}}</td> 
						          <td>{{Categoria.fechaDeRegistro}}</td>
                      <td><a href="{% url 'Productos:editarRegistroCat' Categoria.id %}">Editar</a></td>
                      <td><a href="{% url 'Productos:eliminarRegistroCat' Categoria.id %}">Eliminar</a></td>
					          </tr>

					          {% empty %}
					             <p>No hay productos</p>
					          {% endfor %}
              </table>

            </div>

            <a href="{% url 'Productos:nuevoRegistroCat' %}" class="btn btn-info">Nuevo Registro</a>
          </div>
        </div>
   {% endblock%}

templates/index/index.html
{% extends 'base/index.html' %}
{% load staticfiles %}
}
{% block content %}

<div class="container">

<!-- Categorías-->
<div class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Nota: </strong> <a href="https://github.com/greghernandez/tiendaDjango/blob/master/README.md" class="alert-link">Da clic para ver los datos necesarios para poder realizar una compra </a>
</div>
	<h1>Categorías</h1>

{% for Categoria in categorias %}
    <button class="btn">{{Categoria.nombre}}</button>
{% empty %}
<p>No hay productos</p>
{% endfor %}

<!-- Productos-->
	<h1>Todos Nuestros Productos</h1>
	<div class="row">
	{% for Producto in productos %}
		{% if Producto.cantidad >= 1 %}

		<div class="col-md">
		<div class="card">
    		<div class="card-body">
        		<h4 class="card-title">{{Producto.nombre}}</h4>
        		<h6 class="card-subtitle mb-2 text-muted">${{Producto.precio}}</h6>
        		<p class="card-text">{{Producto.caracteristicas}}</p>
        		<p class="text-secondary">SKU {{Producto.codigo}}</p>
        		<a href="{% url 'Productos:agregarCarrito' Producto.id %}" class="btn">Agregar al carrito</a>
    		</div>
		</div>
		</div>

		{% endif %}
              <!--
                  	<tr>
                  		<td>{{Producto.id}}</td>
						          <td>{{Producto.nombre}}</td>
                      <td>{{Producto.precio}}</td> 
                      <td>{{Producto.caracteristicas}}</td>  
						          <td>{{Producto.codigo}}</td>
						          <td>{{Producto.cantidad}}</td>
                      <td><a href="{% url 'Productos:editarRegistro' Producto.id %}">Editar</a></td>
                      <td><a href="{% url 'Productos:eliminarRegistro' Producto.id %}">Borrar</a></td>
					           </tr>-->

					          {% empty %}
					           <p>No hay productos</p>
	{% endfor %}
	</div>
</div>
{% endblock%}

templates/productos/FormularioAgregarCarrito.html
{% extends 'base/index.html' %}
{% load staticfiles %}
}
{% block content %}

<div class="container">
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="number" name="" value="1" class="form-control" required="" id="">
		<button class="btn btn-success">Agregar al Carrito</button>
	</form>
</div>
{% endblock%}

templates/productos/ProductosFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}
}
{% block content %}

<div class="container">
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-success">Guardar</button>
	</form>
</div>
{% endblock%}

templates/productos/listado.html
{% extends 'base/index.html' %}
{% load staticfiles %}
}
{% block content %}

<div class="container">
      <div class="bs-docs-section clearfix">
        <div class="row">
          <div class="col-lg-12">

            <div class="bs-component">
            	<table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Código</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Editar</th>
                    <th scope="col">borrar</th>
                  </tr>
                </thead>
                <tbody>
                  	{% for Producto in object_list %}
                  	<tr>
                  		<td>{{Producto.id}}</td>
						          <td>{{Producto.nombre}}</td>
                      <td>{{Producto.precio}}</td> 
                      <td>{{Producto.caracteristicas}}</td>  
						          <td>{{Producto.codigo}}</td>
						          <td>{{Producto.cantidad}}</td>
                      <td><a href="{% url 'Productos:editarRegistro' Producto.id %}">Editar</a></td>
                      <td><a href="{% url 'Productos:eliminarRegistro' Producto.id %}">Borrar</a></td>
					           </tr>

					          {% empty %}
					           <p>No hay productos</p>
					         {% endfor %}
              </table>
            <a href="{% url 'Productos:nuevoRegistro' %}" class="btn btn-info">Nuevo Registro</a>
            </div>

            
          </div>
        </div>
      </div>
      {% endblock%}